// Copyright (c) 2023 LogCraft, SAS.
// SPDX-License-Identifier: MPL-2.0

interface plugin {
  /// The metadata for a plugin used for registration and setup
  record metadata {
      /// The friendly name of the plugin
      name: string,
      /// The version of the plugin
      version: string,
      /// The author of the plugin
      author: string,
      /// The description of the plugin. This will be used as the top level help text for the plugin
      description: string,
  }

  // Plugin actions
  load: func() -> metadata;
  settings: func() -> string;
  schema: func() -> string;
  
  // Service actions
  // CRUD definition
  create: func(config: string, name: string, params: string) -> result<option<string>, string>;
  read:   func(config: string, name: string, params: string) -> result<option<string>, string>;
  update: func(config: string, name: string, params: string) -> result<option<string>, string>;
  delete: func(config: string, name: string, params: string) -> result<option<string>, string>;
  
  // Miscellaneous
  ping: func(config: string) -> result<bool, string>;
}