tasks:
  build:
    command: 'cargo build --release'
    deps:
      - '^:build'
    inputs:
      - 'src/**/*'
      - 'Cargo.toml'
  format:
    command: 'cargo fmt --all -- --check'
  test:
    command: 'cargo test'
  clippy:
    command: 'cargo clippy'
  check:
    command: 'cargo check'
  run:
     command: 'cargo run'
     preset: 'server'
  clean:
    command: 'cargo clean'
