on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Checks

permissions:
  contents: read

jobs:
  licenses:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - name: Check license headers
        uses: korandoru/hawkeye@v5