on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Code testing and formatting

jobs:
  validate:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Prepare the toolchain
      - uses: 'moonrepo/setup-toolchain@v0'
      # Check code formatting
      - run: "moon :format --affected --remote"
      # Run tests
      - run: "moon :test --affected --remote"
